stages:
    - build
    - build-docker

build-docker:
  stage: build-docker
  image: docker:stable

  script:
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASS} https://reg.lab.knrg.su
    - docker build -t reg.lab.knrg.su/iskonstantin/moneysaver-nginx:${CI_COMMIT_BRANCH} .
    - docker push reg.lab.knrg.su/iskonstantin/moneysaver-nginx:${CI_COMMIT_BRANCH}
