stages:
  - build-docker

deploy:
  stage: build-docker
  image: docker:stable

  script:
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASS} https://lab.knrg.su:5000
    - docker build -t lab.knrg.su:5000/iskonstantin/moneysaver-nginx:${CI_COMMIT_BRANCH} .
    - docker push lab.knrg.su:5000/iskonstantin/moneysaver-nginx:${CI_COMMIT_BRANCH}
